language: node_js
node_js:
- '9'
services:
- postgresql
before_script:
- psql -c 'create database byob_vehicles_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: OfmI2kxdfLgYgNntMDmGYByd08lZ9+OUx1s/LXpBDrYC7RWZxhQpw59yA3wyQs3pHRMXO7urz7wp7KSJrr5ZX3PIFP0NEkroD2L7jH847Gl4kK6kgUdugBpotDvqMJNJTcMVSLZagXf/P98qBmlZErGgbKieh/jehsBq5/PoRgmXjgg2vshAzQMz6aKekkSAgYjBrxZOkF+CG4yIIEUDVhLVP68v96PidRrW+yZf5Qv/rl7FeOzADijbC32tBaN2/wKVI6+Hp6q+6ShvE/fI3EM9Y4pqzSh3pnBZ3tvauvMfCpKWUhYTOwUKfKJgYG5uIDdmSbMNRyrWdMxvXzUNu1DLbIifkoLiwnrYffOj2AcVA0TWcDLDCX2xhKgyry6NaX2MV/2A9rnE1QKsdHfPFyYPKT6SJdouU044OEL+HMU7LNWH/EsGgyomwjYlwhFGlA+pwww4ngH+RbM9JMCCy6UzH9v2z5q3KSzItRrTaTR0njqIC+Be1E4lm0UsnWxTOLTt27BwJwJgPuTc9Bk3ho9zaift3HqKXbKAhrj8CnnnlnoW54yTEw5JNHBcVdyZXP2rr9ir3AlYr2KKexRzsoK133Yk1NdbTALjjZ5tFJxSL3wYrHeUbscAboi13vgL08smLf3WMzU4cEs/Htu5KWcRRo8BFDg6lh8KoSU9gUU=
  app: car-api-cj
  skip_cleanup: true
