language: node_js
node_js:
- '9'
services:
- postgresql
before_script:
- psql -c 'create database byob_vehicles_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iwpcgpabx2QNZKwhJRLt3t4Ter/MnxMdLYu9qrFOkwgIsMtpDJrOrBp14LfHCsikp13NcyRBkbXx54mR793EJ1GY4We0lV3CYpLsSz/x/uMGVGVkKMi6x5avTTaR4JSbMPvgSf+iXplkrIS6zN/ocoq/6Z45zSd+rdBt9XDeziodV+aunDdInpeLOFScekqRH6dQNr8jkarfiWd4MsUFNaRcJ9Ah7cN1+pX8GYoosiRhQoYlxd1I/Lpbz8e5uS9eZHxpqoI9XVx+9+hTAQ0xzZyK+EzTZU8r9zVgUURUqfWxRh8CRuVgqfJpa4ABdtRCcN0GwbiTyUEG2LXB5wTZU4hViwcc/q8nUGWiNaA6EB2IQvulOzzWZQrzZ8n71ZP9fuWM90Iip6IKa3gk+RCfXDshW2xKhr8kjhrDlmdSC/5yBXCuqu+QpsHT0qS/OVJjrhdQW5yBK+TLgzY/VtjpzwS6jPP0Db7MGaS8Zd510S/PHzgW2JcWFAScYmFP8oPG0XwlMmCwi6gTC6l+7EHl/+AsP0TEEJ/gUOFnFJoPRmEHkVghG/Smc/gQYLnYSiaxc6N+wcDMW/TLCFvGvQLrFW7xPe4q8LH8gfi0IVuI30vCsdRWWEEWdZ7RzgZVt4YstIKewNlixYPSEl3v+tP3yL0UXmPWy+m40di4nzB99Pg=
  app: car-api-cj
  skip_cleanup: true
